# Generated by Django 4.2.7 on 2023-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_blog_user_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя, которое видно всем'),
        ),
    ]
