# Generated by Django 4.2.7 on 2023-11-06 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0003_user_profile_icon_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='test', null=True, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.сhannel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Фотография профиля'),
        ),
    ]
