# Generated by Django 4.2.7 on 2023-11-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=10, unique=True, verbose_name='Имя, которое видно всем'),
        ),
    ]
