# Generated by Django 4.2.7 on 2023-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(max_length=13, unique=True, verbose_name='Номер телефона без +'),
        ),
    ]
