# Generated by Django 4.2.7 on 2023-11-28 13:51

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[users.validators.valid_number, users.validators.valid_number_2], verbose_name='Номер телефона без +'),
        ),
    ]
