# Generated by Django 4.2.7 on 2023-12-01 15:51

from django.db import migrations, models
import django.db.models.deletion
import subscription.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0022_remove_subscriptions_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название Подписки')),
                ('description', models.CharField(max_length=55, verbose_name='Описание Подписки')),
                ('strength_of_subscription', models.IntegerField(validators=[subscription.validators.validate_non_negative], verbose_name='Чем выше число, тем сильнее подписка')),
                ('amount_per_month', models.IntegerField(validators=[subscription.validators.min_sum], verbose_name='Сумма за месяц')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.сhannel')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('name',),
            },
        ),
    ]
