# Generated by Django 4.2.7 on 2023-12-01 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('user',), 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежы'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_nickname',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь!'),
            preserve_default=False,
        ),
    ]
