# Generated by Django 4.2.7 on 2023-11-06 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название поста')),
                ('photo_post', models.ImageField(upload_to='post/', verbose_name='фотография к посту')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание поста')),
                ('likes', models.IntegerField(blank=True, null=True, verbose_name='Кол-во лайков')),
                ('time_the_comment', models.DateTimeField(verbose_name='Дата отправки поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название Подписки')),
                ('description', models.TextField(verbose_name='Описание Подписки')),
                ('profile_icon', models.ImageField(upload_to='subscriptions/', verbose_name='Фотография канала')),
                ('strength_of_subscription', models.IntegerField(verbose_name='Чем выше число, тем сильнее подписка')),
                ('amount_per_month', models.IntegerField(verbose_name='Сумма за месяц')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Сomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=70, verbose_name='Nickname пользователя')),
                ('likes', models.IntegerField(blank=True, null=True, verbose_name='Кол-во лайков')),
                ('description', models.TextField(verbose_name='Комментарий')),
                ('time_the_comment', models.DateTimeField(verbose_name='Дата отправки комента')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Сhannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название канала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание канала')),
                ('profile_icon', models.ImageField(upload_to='channel/', verbose_name='Фотография канала')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('subscriptions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subscriptions')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.сomments'),
        ),
        migrations.AddField(
            model_name='post',
            name='subscription_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subscriptions'),
        ),
    ]
