# Generated by Django 4.2.7 on 2023-11-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сhannel',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Название канала'),
        ),
    ]
