# Generated by Django 4.2.7 on 2023-11-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_сhannel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='сhannel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='сhannel',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.сhannel'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.сhannel'),
        ),
        migrations.AddField(
            model_name='сomments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post'),
        ),
    ]
