# Generated by Django 4.2.7 on 2023-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_subscriptions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='description',
            field=models.CharField(max_length=35, verbose_name='Описание Подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Название Подписки'),
        ),
    ]
