# Generated by Django 4.2.7 on 2023-11-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_subscriptions_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='description',
            field=models.CharField(max_length=55, verbose_name='Описание Подписки'),
        ),
    ]
