# Generated by Django 4.2.7 on 2023-11-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_subscriptions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сhannel',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Описание канала'),
        ),
        migrations.AlterField(
            model_name='сhannel',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название канала'),
        ),
    ]
