# Generated by Django 4.2.7 on 2023-11-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_сhannel_description_alter_сhannel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сhannel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание канала'),
        ),
    ]
