# Generated by Django 4.2.7 on 2023-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_сhannel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='strength_of_subscription',
            field=models.IntegerField(max_length=15, verbose_name='Чем выше число, тем сильнее подписка'),
        ),
    ]
