# Generated by Django 4.2.7 on 2023-11-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_subscriptions_strength_of_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='strength_of_subscription',
            field=models.IntegerField(verbose_name='Чем выше число, тем сильнее подписка'),
        ),
    ]
