# Generated by Django 4.2.7 on 2023-11-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_subscriptions_strength_of_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='profile_icon',
        ),
    ]
