# Generated by Django 4.2.7 on 2023-11-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_subscriptions_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во лайков'),
        ),
    ]
