# Generated by Django 4.2.7 on 2023-11-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сomments',
            name='likes',
        ),
        migrations.AlterField(
            model_name='сomments',
            name='time_the_comment',
            field=models.DateTimeField(verbose_name='Дата отправки комментария'),
        ),
    ]
