# Generated by Django 4.2.7 on 2023-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_post_subscription_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_post',
            field=models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='фотография к посту'),
        ),
    ]
