# Generated by Django 4.2.7 on 2023-11-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_post_photo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сhannel',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='channel/', verbose_name='Фотография канала'),
        ),
    ]
