# Generated by Django 4.2.7 on 2023-11-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_сhannel_profile_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(max_length=10, verbose_name='Пользователь')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], max_length=10, verbose_name='Способ оплаты')),
                ('subscriptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subscriptions', verbose_name='Оплаченная подписка')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежы',
                'ordering': ('user_nickname',),
            },
        ),
    ]
