# Generated by Django 4.2.7 on 2023-11-18 15:30

from django.db import migrations, models
from subscription import validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='amount_per_month',
            field=models.IntegerField(validators=[validators.min_sum], verbose_name='Сумма за месяц'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='strength_of_subscription',
            field=models.IntegerField(validators=[validators.validate_non_negative], verbose_name='Чем выше число, тем сильнее подписка'),
        ),
    ]
