# Generated by Django 4.2.7 on 2023-11-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_subscriptions_amount_per_month_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
