# Generated by Django 4.2.7 on 2023-12-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='channel',
        ),
    ]
