# Generated by Django 4.2.7 on 2023-12-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_subscriptions_channel'),
        ('subscription', '0001_initial'),
        ('payment', '0003_alter_payment_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subscription_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscriptions'),
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
