# Generated by Django 4.2.7 on 2023-12-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_post_subscription_level_delete_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сomments',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Сomments',
        ),
    ]
